### ISSUE TITLE
add multiline selection for feeds to add under a same category

### ISSUE THREAD

**Issue by C00kie-** [cedricbonhomme/newspipe#42]
Hello, this is for when you import multiple feeds that you want to put under the same category.
Thanks

**Comment by cedricbonhomme** [comment]
Hi,
yes, I can do something for this.
I just pushed a little improvements for the list of feeds of the home page. Feeds are now finally sorted per categories. Already on production.

I will add a way to change the category of a set of feeds more easily.
Also I can add the import of categories when importing an OPML file. I need to check that too.

I also created a ticket [here](https://todo.sr.ht/~cedric/newspipe/6) for this (you can create ticket without account via email).

**Comment by cedricbonhomme** [comment]
first point: https://todo.sr.ht/~cedric/newspipe/6

**Comment by C00kie-** [comment]
Thanks a lot! 
Drag and drop will be useful too, that's a great idea.
