### ISSUE TITLE
Documentation on LDAP use

### ISSUE THREAD

**Issue by Gorneman** [cedricbonhomme/newspipe#76]
Hi, where I can find some documentation on How to use LDAP with it? Thanks

**Comment by cedricbonhomme** [comment]
Hi,

Normally all you have to do is to enable it and configure it:
https://github.com/cedricbonhomme/newspipe/blob/master/instance/config.py#L78

**Comment by Gorneman** [comment]
Thanks. Mistake in LDAP Filter.
